environment:

  matrix:
    - PYTHON: "C:\\Python37"
      TOXENV: py37-test

install:
  - "%PYTHON%\\python.exe -V"
  - "%PYTHON%\\python.exe -m pip install tox"
  - "%PYTHON%\\python.exe -m pip install codecov"
  - "%PYTHON%\\python.exe -m pip install coveralls"
  - "%PYTHON%\\python.exe -m pip freeze"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox -vv -e %TOXENV%"

after_test:
  - "%PYTHON%\\python.exe -m coveralls"
