# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
    # Doctr deploy key for goerz-forks/pypkg_x8uqn
    - secure: "A3UEUtDcn9kjMssJKPA5RgzDyu0/nEFdCRSnXrM9gvr5dFxxaJkQjmqMbJwUJkAIVzJldq3YveMb0SrmE2Obm35eISGgeushuVBRoL6SwtqDb0pNUlKdS8f63/jJwRpW0JiBqgOOUPKHH3ZDU/2nkZSvoVe2lCwV3SRWxVjPFFOgJHn/S9QVIi1kIcVF8wV5nIApTHK2hxssrz5PQ9xq6P3zkfAtH8k7lISC8AJsS1LdZRp4C79YfV4Vp8qucLLXrtU0+0Vu0opzO7ZJVyZU8Su+xCMkddmBmcgcZcd3lZiNHYnusBL+Yokxsa0mEZgh72CsBVyQZtWcnQDn92CDcEIWTEtvErInVDSTwfwY9yYO3IqLyvmBA0PrffGqjD+dLGDLOa7jEjryuhS4aaf4TpIuGjLs2pRY6ZO03ZwEnvL5jUHvCZv2vAzE9XyAwFcbcrj8F0tKeieqChEm9TmphHTAxfpLxWJ2dELpxdzWTx/E9/Fm+RpSEVBOXv/p3tA6zv5zyY4NquUI4MpG4GOVq6fgrq+qoRDrMfPJGu/MfdNPmRbnHfw/GBHHBTKL9xzyfPaTTP2Jlmrww576V1J0tPSNnND4diOTQ/hezfb/ZNLfjtGBIARDbPwbuwrOFL4PENGfX5AZzP0pVTDcvNiHlvgVfx/9UfzM2h3hRgZPo5s="
    - CODECOV_TOKEN="a2f5565d-d5ca-43a0-98c0-ccb61ff025c0"
matrix:
  fast_finish: true
  include:
    - name: Check codestyle
      python: 3.7
      env: TOXENV="run-blackcheck,run-isortcheck"
    - name: Docs
      python: 3.7
      env: DOCS="true"
      addons:
        apt_packages:
          - pandoc
    - name: Python 3.6
      python: 3.6
      env: TOXENV=py36-test
    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37-test
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-test

install:
  # any failure stops the build
  - set -e
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - pip install tox
  - pip install 'coverage<5.0' coveralls
  - pip install 'coverage<5.0' codecov
  - pip freeze
  - printenv
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  # any failure stops testing immediately
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/doctr_build.sh
    else
      tox -e $TOXENV
    fi
  - echo "DONE"
after_success:
  - if [[ "${TOXENV}" =~ test ]]; then codecov; fi
  - if [[ "${TOXENV}" =~ test ]]; then coveralls; fi
